---
- name: Check if restic is installed
  ansible.builtin.command:
    cmd: /usr/local/bin/restic version
  ignore_errors: true
  changed_when: false
  register: check_restic_version

- name: Install restic binary
  when: check_restic_version is failed or restic_client_version not in check_restic_version.stdout
  block:
    - name: Download compressed restic
      ansible.builtin.get_url:
        url: '{{ restic_client_repo_url }}/releases/download/v{{ restic_client_version }}/{{ restic_client_archive }}'
        checksum: 'sha256:{{ restic_client_repo_url }}/releases/download/v{{ restic_client_version }}/SHA256SUMS'
        dest: /tmp/restic_{{ restic_client_version }}.bz2
        owner: root
        group: root
        mode: '0644'
      vars:
        restic_client_archive: restic_{{ restic_client_version }}_{{ restic_client_platform }}_{{ restic_client_arch }}.bz2

    - name: Decompress restic
      ansible.builtin.command:
        cmd: bzip2 --decompress /tmp/restic_{{ restic_client_version }}.bz2
      changed_when: false

    - name: Ensure restic is installed
      ansible.builtin.copy:
        src: /tmp/restic_{{ restic_client_version }}
        dest: /usr/local/bin/restic
        remote_src: true
        owner: root
        group: root
        mode: '0755'

    - name: Ensure temporary file is removed
      ansible.builtin.file:
        path: /tmp/restic_{{ restic_client_version }}
        state: absent
